### ISSUE TITLE
permanent data for grafana container - retain config and dashboards

### ISSUE THREAD

**Issue by ryebreadsalad** [industrial-edge/archiving-and-visualization#4]
Hi, can you please add permanent data for grafana so you can retain the dashboards?

e.g. 

volumes:
    - grafanaconfig:/etc/grafana
    - grafanadata:/var/lib/grafana

Thanks

**Comment by Boehmi-TB** [comment]
Thanks for suggesting this enhancement for this project.
This will be implemented in the upcomming version

**Comment by Boehmi-TB** [comment]
@ryebreadsalad 
can you share the source with the information to use volumes for:
volumes:
- grafanaconfig:/etc/grafana
- grafanadata:/var/lib/grafana

According to https://grafana.com/docs/grafana/latest/administration/configure-docker/#run-grafana-container-with-persistent-storage-recommended only /var/lib/grafana is needs to be mounted to persist data
