### ISSUE TITLE
Used versions

### ISSUE THREAD

**Issue by HummelN7872** [industrial-edge/archiving-and-visualization#6]
Please adapt the used version to the exact version and do not refer to a > V X.Y, but to the dedicated version to tested the How To

OS: Windows or Linux
Docker minimum V18.09
Docker Compose V2.0 – V2.4
Industrial Edge App Publisher (IEAP) > V1.0.8
Industrial Edge Management (IEM) > V1.0.10
S7 Connector > V1.0.22
S7 Connector Configurator > V1.0.9
IE Databus > V1.0.11
IE Databus Configurator > V1.0.44
Industrial Edge Device (IED) > V1.0.0-43
TIA Portal V16
PLC: CPU 1511 FW 2.8.3

**Comment by HummelN7872** [comment]
Additional, are the version up to date? Did you already tested with V1.2?

**Comment by BrotKolben** [comment]
Updated used versions and tested with V1.2.

**Comment by EndyCZ** [comment]
Closed by #7 .
